name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Save merged branches
        run: echo "${{ github.event_name }} event triggered for ${GITHUB_REF#refs/heads/}" >> merged_branches.txt
